### ISSUE TITLE
Type inference for binary operators has inconsistent output

### ISSUE THREAD

**Issue by kach** [querycert/qcert#103]
The order of the elements in the output of `infer_binary_op_type_sub` isn't consistent across the various operators. For example, `OpLt` returns `Some (Bool, Nat, Nat)`, i.e. `(output, input, input)` ([source](https://github.com/querycert/qcert/blob/82140000b2d63b6c1eb06aa8804d879559a3b3fa/coq/Common/OperatorsTyping/TOperatorsInferSub.v#L97)), whereas `OpFloatCompare` returns `Some (Float, Float, Bool)`, i.e. `(input, input, output)` ([source](https://github.com/querycert/qcert/blob/82140000b2d63b6c1eb06aa8804d879559a3b3fa/coq/Common/OperatorsTyping/TOperatorsInferSub.v#L132)). This makes it hard to extract the output type of a binary operator in [Ergo](http://github.com/accordproject/ergo), a language we're building using QCert.

(cc @jeromesimeon)

**Comment by jeromesimeon** [comment]
That bug's traced back to https://github.com/querycert/qcert/commit/970b735f126e887d35107689653c8923fa5846e8#diff-82edd685eaa31ee967ad91b372aa89d3

**Comment by jeromesimeon** [comment]
Also tested in Ergo now, closing the issue.
