### ISSUE TITLE
WASM: Functional Operators

### ISSUE THREAD

**Issue by pkel** [querycert/qcert#148]
While implementing the Wasm runtime in Assemblyscript, I paid no attention whether the operators are mutating values in place or not. Q*cert assumes that they are not. We have to ensure that the operators respect this assumption.

This is particularly interesting for arrays. I think, the current JS runtime avoids copying on each push by allocating bigger arrays  and keeping track of the length separately.

**Comment by jeromesimeon** [comment]
> This is particularly interesting for arrays. I think, the current JS runtime avoids copying on each push by allocating bigger arrays and keeping track of the length separately.

An example of that strategy can be found in the JavaScript runtime. See some parts of that here:

https://github.com/querycert/qcert/blob/0f07b1cd6c2ca53330dc0290d5d7a64a542116b4/runtimes/javascript/qcert-runtime-core.js#L27-L40

Or here:

https://github.com/querycert/qcert/blob/0f07b1cd6c2ca53330dc0290d5d7a64a542116b4/runtimes/javascript/qcert-runtime-core.js#L190-L207

**Comment by pkel** [comment]
The existing operators do not mutate values. I will close this issue.

At some point in the future we might want to think about speeding up opArrayPush. Currently it naively clones the array on each invocation. I think we have other, more important tasks right now.
