### ISSUE TITLE
Provide CAMP evaluator in Java-callable form

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [querycert/qcert#17]
The CACoEngine API does not currently include the CAMP evaluator.   In order to test Java code that is translating to CAMP, this would be very useful since it is the shortest path to a valid test (otherwise, one needs to choose a back end and use a complete end-to-end test).

**Comment by joshuaauerbachwatson** [comment]
As noted in the description, I _do_ have the option of using an end-to-end test with the Java or Javascript backend in lieu of a CAMP evaluation test.  While this is less "minimal" it will suffice.  Probably the biggest headache in constructing tests is the fact that you need data in addition to code ... this will be true of any test regardless of whether it is end-to-end or employs an evaluator.

So, I would not classify this request as urgent.

**Comment by jeromesimeon** [comment]
Hi Josh, Thanks for recording this issue. I've been thinking about it a bit more and yes the main question is how do we want to ingest data. As of now we do not have a very uniform/well defined way to do so, and if we expose eval in the Java API, changes in the underlying API for evaluation in OCaml will have to be reflected in Java.

My current preference would be to first cleanup the corresponding part in the Coq/Ocaml side, and wait until we have a more well defined API for data loading and eval to expose that in Java.

**Comment by joshuaauerbachwatson** [comment]
As the original author of this issue, I'm taking the liberty of closing it because (1) the specifics of using Java as the calling language are now obsolete, and (2) a similar issue (using Javascript rather than Java) is going to come up and be addressed in the planned sigmod demo.
