### ISSUE TITLE
Obsolete material in samples/Makefile

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [querycert/qcert#18]
The Makefile in the samples directory includes targets to drive our compiler as well as the target to build the runners and the targets to run things.  The README skirts discussion of the compile targets, but they can still get activated if a manual build via bin/qcert was not done.  If that happens, the makefile will attempt to run the now-gone CACo binary.

**Comment by jeromesimeon** [comment]
Thanks for reminding me. I think I've fixed that issue, but on the sql branch so I'll have to pull this change back into master. It may not happen immediately so let's leave this issue open for now.

**Comment by jeromesimeon** [comment]
The fix for this has now been merged. I'm closing this issue.
