### ISSUE TITLE
Facilitate Rule/CAMP input by providing Java AST classes

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [querycert/qcert#2]
The qcert binaries accept both `-source Rule` and `-source OQL`.    Current samples stress OQL.

The "Rule" case means CAMP (Calculus for Aggregating Matching Patterns) augmented with a set of macros defined over CAMP called Rules.  The paper designed SSH15 in the README.md describes the initial versions of these languages (the CAMP language has since evolved modestly).

To facilitate the constructions of new front-ends for other query languages, this issue proposes to expose CAMP and Rules in the form of AST classes in Java.  ASTs can be constructed in Java, emitted to the appropriate linear syntax, and fed to the CACo or CAEv binaries.

**Comment by joshuaauerbachwatson** [comment]
It appears I am not authorized to self-assign issues.   However, you can consider me signed up to work on this with no specific timetable.

**Comment by jeromesimeon** [comment]
Hi Josh, I looked into it, and it seems that to be assigned that issue, you would need to be in the 'organization'. I did invite you, but I'm not sure if you accepted. If you feel like, I believe we would all be glad to have you on board. As far as I can tell, this doesn't need to affect the workflow you use (fork v branch).

**Comment by joshuaauerbachwatson** [comment]
Thanks for the clarification.  I didn't know the invitation was there ... as far as I can see it only shows up on the members page and even there it is easy to overlook.   I accepted and am now a member.

As you indicated, I am still following the practice of committing only to my fork, at least for now.

**Comment by joshuaauerbachwatson** [comment]
There are two ways to integrate Java front-end code with the qcert compiler: one can emit text into files and then invoke the CACo compiler in a separate process or one can build the CALib.jar, then use it to invoke qcert in-process on in-memory text.

Both because it is more convenient for Java integration and because it has cleaner capabilities for parsing, I prefer to use the CALib.jar approach.   However, I am currently blocked on problems described in issue #1.

**Comment by jeromesimeon** [comment]
Note: part of this issue has been address, merging Josh's additions of a JAVA AST for CAMP. The second part of that issue (that of using CALib.jar as a compiler for that AST) is still pending.

**Comment by joshuaauerbachwatson** [comment]
I am going to close this issue for the following reasons.

1.  A basic Java AST for Rules and CAMP exists and is present in the main code repository, so that part is done.

2.  We no longer maintain and use the CALib.jar approach.   A Java-callable library could be constructed using qcertJS.js (a Javascript library which we do maintain), with a Java veneer.  But, that piece of work awaits a real motivating use case which we don't have at the moment.

3.  CAMP and Rules are only interesting intermediate languages when the front-end language is a rules language but much of our recent work has focused more on real query languages like SQL.   The translation chain for SQL bypasses CAMP and Rules and goes directly to NRAenv (as with OQL).  We would need ASTs for all more of our intermediate languages (not just Rules and CAMP) to complete the project.  Again, we await a motivating use case.  We are supporting SQL in a different way (by calling out to Java in a separate process passing strings, rather than using a Java-callable library).

4.  If we ever have a motivating use case to revive this work, we should at least explore drawing on work that was done at IBM to support the ODM product.  This is not open source but perhaps could be.
