### ISSUE TITLE
Support global queries authored in ODM Insights Designer

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [querycert/qcert#35]
Our current JRules support is based on capabilities that are common to both the (standard) ODM Rules Designer and the Insights Designer that comes with ODM Advanced.   So, it is incapable of handling languages (like the global queries language) that are only in Insights.   Historically, the IBM Internal project that gave rise to this one did support that language.  It would be nice to do so because it is a true query language and not a production rule language being reused as a query language (see issue #34).  Also, examples of it appear in some of our papers.

There are two issues in resurrecting this support publically.

First, code that depends on having a copy of the Insights Designer needs to be cleanly separated from other JRules support so that researchers who have obtained only the Rules Designer can still use the support.

Second, we would need to know that researchers will have a pathway for obtaining the Insights designer.  Right now the easiest pathway for obtaining any Designer product is the ODM Cloud free trial, and that only provides the Rules Designer.

**Comment by joshuaauerbachwatson** [comment]
Note that the second question posed in the description is non-technical.  I know that in the past IBM has had programs that make some products available for free to academics for research and teaching purposes.  I don't know if that program still exists or whether ODM Advanced is on the list.  I believe one or more of my colleagues still at IBM would have to investigate this.

What I didn't mention in the description is that I myself have no copy of ODM Insights Designer and no way of obtaining one legally on my own (that I know of).   So, I will remove myself as assignee from this issue (since I can do nothing more about it) until there is more news.

**Comment by joshuaauerbachwatson** [comment]
This issue recently came up in discussion.  I should note that I have since found links to the current incarnation of the "IBM Academic Initiative", which still includes lots of free licenses to IBM software.   It is a little hard for me to figure out exactly what's there, because I cannot create an account for myself (I don't have an affiliation with an academic institution that I can use for the purpose).   However, ODM is definitely NOT mentioned in any of the accessible pages.

**Comment by jeromesimeon** [comment]
I'm not sure what the status of this issue is. Has this been resolved through the TechRule/DesignRule support, or is this still open?

**Comment by joshuaauerbachwatson** [comment]
The issue is still open.   It can be confusing, because there are two orthogonal distinctions.

1.  The distinction between technical rules and designer rules.

2.  The distinction between the "Rules" Designer and the "Insights" Designer.

We DO support both technical rules and designer rules.  However,

We DO NOT support the Insights Designer, only the Rules Designer.

Each designer brings along its flavor of designer rule languages.   In the Rules Designer, the key language is BAL, which is a production rule language.   There is no query language in the Rules Designer.   In the Insights Designer there is both BERL (a production rule language) and DEFL (a query language).   We use DEFL examples in some of our papers, so it would be nice if the open source Q*Cert supported DEFL.

I would really like to work on this but I cannot because I cannot get a copy of the Insights Designer as a member of the general public not willing to pay for an ODM Advanced license.

**Comment by jeromesimeon** [comment]
Won't support, I don't think. Closing this.
