### ISSUE TITLE
S-expression parsing doesn't get floating point right

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [querycert/qcert#36]
I noticed this problem when attempting to feed some JRules that have floating point literals in them through the latest system.   I have fixed sexp_to_data by adding a clause for floating point literals (and will commit and push that partial fix).  However, this leaves the AstToSExp system in a state where sexp_to_data and data_to_sexp are not inverses.  This happens because both floating point and "dtime_scale" are foreign types and the "dtime_scale" case (do we even use this any more?) was hijacking the entire foreign type subsystem of s-expression data parsing.   The fix was straightforward in the direction I fixed but I'm not sure how to fix the other direction, so it is still hijacked.   Concretely, if you feed in (Pconst 0.3) as input CAMP and ask for a dump back from qcert, it comes back as (Pconst (dtime_scale "0.3")).

Asking for help in completing the fix.

**Comment by jeromesimeon** [comment]
I've just pushed a fix for this. Foreign data was always turned into a time scale (clearly a bug). There might still be specific serialization issues on floating points, but (Pconst 0.3) is properly dumped back to (Pconst 0.3).

**Comment by joshuaauerbachwatson** [comment]
I'm closing this (since it's a bug report that I opened).  I think Jerome's fix is good enough.  In theory we could devise some unit tests to show that it's completely fixed, but in practice, "sufficient unto the day."
