### ISSUE TITLE
Provide the CALib material in built and downloadable form

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [querycert/qcert#4]
This is a selfish request.  For most people, the procedure described in the READMEs in the ocaml directory will probably allow CALib.jar to be built.  This jar is useful when writing Java front-ends or Java drivers for the qcert compiler.

However, there is no path for building this jar on a 32-bit windows system, which is what I have.  And, I would very much like to work on Java front ends for qcert as noted in issue #2.  So I humbly request that a built copy of CALib.jar be included somewhere in the repository for use by those not in a position to build it from scratch.

**Comment by joshuaauerbachwatson** [comment]
Having discussed this with Jerome, I think the issue won't be acted on as stated: there is understandable reluctance to commit a derived artifact to a source repository.  I've changed the title to suggest that, if any binary form is provided, it should be positioned as a download or extra artifact and not be committed to the source repository.

I also think that if issue #3 is addressed in any form, windows instructions should specify that you must have a 64 bit version.  My situation is too idiosyncratic to induce a general solution.   Note that all practical ways of installing OcamlJava require 64 bits (and the circumvention of running linux in a VMWare player is not available either since that also requires 64 bit windows).    I will probably have either a Mac or a 64 bit windows machine by some time in the fall so hopefully I'm the last outlier.

**Comment by joshuaauerbachwatson** [comment]
@jeromesimeon has started providing  QcertLib.jar in binary form through the gitlab "release" mechanism.  This satisfies my needs.   I would close this except that I'm not sure whether he wants to go to a more fully automated approach though the build server so I will leave it up to him whether to close this issue.

**Comment by jeromesimeon** [comment]
Thanks for the reminder. Yes I'd like to keep this issue open to keep track of this. The current approach requires one of the developers to upload a fresh version of QcertLib.jar in binary form at regular intervals (when the code changes). It would be good to have a more automatic way to publish the jar.

**Comment by joshuaauerbachwatson** [comment]
This is obsolete since we no longer use a Java library jar but have a Javascript artifact that takes its place.  I have no problem building that artifact, so the "selfish" reason for this issue is gone.
