### ISSUE TITLE
compileForEval not working in either demo version

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [querycert/qcert#44]
In the samples directory, the following works and produces a plausible answer:

`../bin/qcert -source oql -target nnrc -eval -input data/persons.oql.input -schema data/persons.oql.schema oql/test1.oql `

Omitting the schema makes no difference but if I omit the input I get

`{"error": "Eval failed"}`

as one might expect.   When I use the qcert.html version of the demo, to which @jeromesimeon recently added **compileForEval**, I get the same sort of error for the same evaluation, even though I am supplying the input and it appears to be present in the config structure being passed to the compiler.

I have merged the logic from qcert.html into demo.html.  It fails there also.

**Comment by joshuaauerbachwatson** [comment]
This appears largely fixed.   However, while I am able to get (e.g) oql->nnrc compilation and evaluation to work, I cannot get sql->nnrc evaluation to work (compiles fine, evaluation produces an uninformative error).   This is true of both the small examples in samples/sql and larger ones in samples/sql/tpc.   I haven't tried other source languages.

**Comment by joshuaauerbachwatson** [comment]
Addendum to previous: I tried a tech_rule example (evaluating the nnrc) and that worked also.  So far, then, I've only observed problems when the source language is SQL.

**Comment by jeromesimeon** [comment]
I couldn't find a way to make it work, until I remembered that the SQL parser turns all names into lower case. Using a schema/data with lowercase constants, I was able to run the SQL compiler and exec from the demo. Do you think that might be the problem you were having?

**Comment by joshuaauerbachwatson** [comment]
Responding to @jeromesimeon.  It's possible that that's part of the problem but I'm not sure it's the entire problem.   I've tried two cases:

Case 1: s2.sql from samples/sql, with persons.sql.json from samples/data

Case 2: tpch_6.sql from samples/sql/tpc, with tpch.data from the same folder

In case 1, the supplied data file uses mixed case names for the tables "Persons" and "Companies" and BOTH nnrc eval and js eval fail.  When I change those names to lower case BOTH nnrc eval and js eval succeed.

In case 2, js eval succeeds without any changes, and nnrc eval fails, albeit differently.  I don't offhand see where there are any mixed case identifiers in the data file but it's big and I'm not 100% sure.  Certainly the table names are lower case.

Could you see if you can reproduce my results for case 2 and get to the bottom of that?  It may be a separate issue.  Also, I think that

- IF there is a medium term restriction that all identifiers in SQL must be lower case, we should supply only samples that conform to that

- we should certainly not make that a long-term restriction: we should be consistently using mixed case comparisons when semantics of the identifers require it.  The evidence is that all of our evaluators (including Javascript) may need adjusting for this.

**Comment by joshuaauerbachwatson** [comment]
I can now more precisely pinpoint what does and doesn't work.

- As discussed, it appears the all evaluations (including Javascript) fail if they rely on 'ignore case' semantics for comparisons of names.   This is correctable by ensuring consistent case (but this is a bandaid)
- All examples that use the current TPC dataset will fail because qcert code seems unable to parse negative floating point numbers that appear in JSON input.  There are two such numbers in the dataset.  This is correctable by hacking the numbers (removing the minus signs).  This problem does not affect Javascript evaluation
- It appears that TPC examples that use dates also fail, even if the previous is corrected.  For example, after correcting the previous, tpch_1 and tpch_6 fail but tpch_16 succeeds.
-

**Comment by joshuaauerbachwatson** [comment]
The title, description, and comment history of this issue have become misleading.  I think it would better to close this issue and open three small focused issues, which I am about to do.  The issues will concern
- the gnarly question of whether SQL identifier comparison does or does not respect case
- the bug in JSON parsing in qcert whereby -10 is legal and 10.2 is legal but -10.2 is (erroneously) illegal.
- support for SQL dates in coq code
