### ISSUE TITLE
Interface Q*cert with Hyperledger composer

### ISSUE THREAD

**Issue by jeromesimeon** [querycert/qcert#78]
The Hyperledger composer includes a data model and (small) query language. It would be interesting to try Q*cert as a query compiler in that context.

**Comment by shinnar** [comment]
There is some initial work towards this on the blockchain branch.

**Comment by jeromesimeon** [comment]
Hyperledger Composer is now deprecated https://github.com/hyperledger/composer

I think this issue is a "won't support" kind at this point.

Note that support for composer models based on the Q*cert type system is available in https://github.com/accordproject/ergo
