### ISSUE TITLE
Build server

### ISSUE THREAD

**Issue by fehrenbach** [querycert/qcert#8]
We should set up a build/test server.
I have used Travis CI before, it is free for open source projects and you can get OPAM to work with some fiddling.
I have also heard good things about CircleCI, but have not used it. They seem to have free plans for open source projects, too.

We could use this to automatically publish snapshots of the ocamljava-built jar to a maven repository, or upload as a release to github, addressing #4.

**Comment by jeromesimeon** [comment]
I think that's a great idea. I had seen Travis and thought it might be a good choice, but they didn't list support for Ocaml, so I didn't dig deeper. Any help/advice on how to set it up, and get opam to work on it, would be great.

**Comment by fehrenbach** [comment]
I have a branch in my clone with Travis support. Unfortunately it times out. A clean build of QCert takes almost an hour. And we have to build Coq, because adding the OPAM repository breaks the binary Coq package, or something... The time limit is 50 or 45 minutes or something on Travis.

I also have a branch with CircleCI support. They have a 2 hours build time limit, if I recall correctly. I managed to build the Coq code, the OCaml code (to native code), and the Spark2 runtime. I haven't tried the Java runtime, but that should work. I have yet another branch (I think I'm turning into Avi) that tries to build using ocamljava, but that doesn't work yet.

**Comment by jeromesimeon** [comment]
Wow. That's great. I may be able to help with the ocamljava side, if I can see some traces.

**Comment by fehrenbach** [comment]
I filed a Coq bug on the extracted name change for our rtype₀ constructors: https://coq.inria.fr/bugs/show_bug.cgi?id=5000

**Comment by fehrenbach** [comment]
So, apparently that was intentional, i.e. it's not going to get changed again, so if we want to move to 8.5pl2 we will have to apply this patch: 5dc740137ed2a12de8213aa9c28a700b8f2788c7

**Comment by jeromesimeon** [comment]
We have switched to coq 8.5pl2 and enabled CircleCI. Further adjustments to the builds could be made, but  I think we can consider this issue closed.
