### ISSUE TITLE
Create a more imperative variant of nnrc

### ISSUE THREAD

**Issue by shinnar** [querycert/qcert#89]
this will be called nnrc_imp.  The plan is to translate from nnrc to it (possibly going through some other transformations first to help stratify statements and expressions).

- [x] Define nnrc_imp syntax and semantics
- [X] Define type system stuff for nnrc_imp
- [x] Translate from nnrc to nnrc_imp
- [x] Prove that the translation is type preserving
- [x] Add support for nnrc_imp to the driver and such

**Comment by shinnar** [comment]
Removed the part about compiling from nnrc_imp to backends, as that will be handled by other issues such as #92 .

**Comment by shinnar** [comment]
Added type system with type soundness result.

**Comment by jeromesimeon** [comment]
🕺
